language: en
pipeline: supervised_embeddings
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.3
  core_threshold: 0.3
  fallback_core_action_name: "action_default_ask_affirmation"
  fallback_nlu_action_name: "action_default_ask_affirmation"
  deny_suggestion_intent_name: "out_of_scope"
